hepsi:derle bagla calistir

derle:
	g++ -c -I "./include" ./src/main.cpp -o ./lib/main.o
	g++ -c -I "./include" ./src/Kuyruk.cpp -o ./lib/Kuyruk.o
bagla:
	g++ ./lib/main.o ./lib/Kuyruk.o -o ./bin/program.exe
calistir:
	./bin/program